#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappDeployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: java
  tempalate:
    metadata:
      name: javapod
      labels:
        app: java
    spec:
      Containers:
      - name: javawebappcontainer
        image: dockeruma03/javawebapp:1
        ports:
        - ContainerPort: 8080
#Service
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: ClusterIP
  selector:
    app: java
  ports:
    - port: 80
      targetPort: 8080
